#! /bin/sh

sxhkd &
feh --bg-fill --randomize ~/distroTube/wallpapers/ &
unclutter &
compton -f -D 3 &
xinput set-prop 10 306 1 & xinput set-prop 10 314 1 &
setxkbmap -option caps:escape
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 			 5 
bspc config top_padding                   24
bspc config top_monocle_padding 	  0
bspc config border_width 		  2
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle                true
bspc config focus_by_distance true
bspc config paddingless_monocle true
bspc config focus_follows_pointer false
bspc config ignore_ewmh_focus true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Colors
bspc config active_border_color \#8FBCBB
bspc config focused_border_color \#00FFFF
bspc config normal_border_color \#2E3440

# Rules

bspc rule -a discord desktop='^8'
bspc rule -a feh state='floating'
bspc rule -a mpv state='floating'
bspc rule -a pavucontrol state='floating'
bspc rule -a *:SPLASH state='floating'
bspc rule -a kitty state='floating'
bspc desktop -f 1

#~/.config/bspwm/autostart &
xsetroot -cursor_name left_ptr &
dunst &
redshift -x && redshift -O 4000 &
pulseaudio &
nm-applet &
kitty service bluetooth start &
blueberry-tray &

